Repository adithyapaib/cheems, pull requests merged in 2020-10, with the labels that each got.

#4 Improved Responsiveness
  index.html
Labels: hacktober-fest

#7 add dogo meme
  assets/img/Original_Doge_meme.jpg
  index.html
Labels: hacktober-fest, hactoberfest-accepted

#6 add new image
  README.md
  human-dog.jpg
Labels: hactoberfest-accepted
